### PR TITLE
Restore all telemetry node fields which were removed previously for backend

### PR DESCRIPTION
**Pull request by i1i1**

### CODE REVIEW

**Comment by i1i1** [comment]
Just in case. I partially restored changes from #26

**Review by nazar-pc — APPROVED** [review]
Looks okay to me

**Comment by nazar-pc** [comment]
@i1i1 why was this merged into `lz4` branch?

**Comment by i1i1** [comment]
I believe we deployed from that one. I guess we need to rename it. Would `dev` or `subspace-customizations` sound better?

**Comment by nazar-pc** [comment]
I'm not sure about that, `subspace-customizations` already exists and has more commits that `lz4` branch, from which I make a conclusion that `lz4` probably was never actually deployed. It was just a branch where you tried to do compression, but we ended up not using it.

**Comment by i1i1** [comment]
Oh, makes sense. I will cherry-pick commits on top of `subspace-customizations`

**Pull request merged**
