### PR TITLE
Fix typo incrementing instead of decrementing

### PR DESCRIPTION
**Pull request by clostao**
This PR solves the label (network name) issue in Subspace Telemetry where Taurus testnet is sometimes labeled as Autonomys Mainnet. 

The issue is that for determining the label of the network it's used a voting-like system in which when nodes start sending telemetry logs also send its network information  (genesis hash, network name, etc.). For each genesis hash the network name that has been sent the most times is the one to be shown. 

The issue was that when a node lost connection with telemetry instead of decreasing the number of votes from the network name they voted the service was increasing the number of votes, leading to a corruption of the voting. With the current fix, as long as the number of nodes sending the correct network name remains higher from those sending a wrong name, the correct label should be shown.

That being said this highlights an underlying issue in which some nodes are sending telemetry logs with the wrong network name but the correct genesis hash. I'll be looking for that error but this should solve the issue of wrong network label.

### CODE REVIEW

**Comment by nazar-pc** [comment]
Can you submit this upstream as well?

**Comment by clostao** [comment]
> Can you submit this upstream as well?

Sure, [here it is](https://github.com/paritytech/substrate-telemetry/pull/595)

**Review by marc-aurele-besner — DISMISSED** [review]
LGTM

**Review by teor2345 — DISMISSED** [review]
Looks good!

**Comment by teor2345** [comment]
I pushed a commit with tests that check for this bug. Detailed reproduction steps are in the commit message, and the test comments.

**Review by marc-aurele-besner — APPROVED** [review]

**Comment by clostao** [comment]
Can't approve but LGTM

**Review by nazar-pc — APPROVED** [review]

**Comment by teor2345** [comment]
Upstream has reviewed and approved it as well, so I think we can merge.

Edit: upstream does squash merging, so I merged it that way to avoid merge conflicts.

**Pull request merged**
